Add CodeMirror syntax highlighting to form fields
awesomemotive/insert-headers-and-footers pull request #7
Opened 2020-06-09 17:47 UTC by bradp

Adds CodeMirror functionality from the theme/plugin file edits into our fields.

![Screenshot 2020-06-09 12 46 34](https://user-images.githubusercontent.com/66798/84181966-48e00280-aa4f-11ea-91f0-dbb36bb4a9d5.png)

2020-06-09 17:54 UTC, bradp commented on ihaf.php
> + 		// Enqueue code editor and settings for manipulating HTML.
This needs to run only on our settings page

2020-06-12 13:54 UTC, bradp commented
> Unless I'm missing it, this would throw errors on WP < 4.9 since the `wp_enqueue_code_editor` was not introduced until then.

Added a check for this.

2020-10-14 22:47 UTC, peterwilsoncc requested changes
LGTM, labeling with change request so I remember to deal with my nits.

2020-10-14 22:47 UTC, peterwilsoncc commented on ihaf.php
> + 		if ( ! ( $pagenow == 'options-general.php' && isset( $_GET['page'] ) && $_GET['page'] == 'insert-headers-and-footers' ) ) {
Nits: `===` (I'll deal with this)

2020-10-14 23:12 UTC, peterwilsoncc approved these changes

2020-10-25 23:02 UTC, merged